### ISSUE TITLE
database

### ISSUE THREAD

**Issue by xaxiris** [ellak-monades-aristeias/WeatherPiStation#2]
Πρόσθεσε το σχήμα της βάσης

**Comment by mbalamat** [comment]
Κάνω ένα προσχέδιο της βάσης και το στέλνω να το κάνουμε review.

**Comment by mbalamat** [comment]
Αυτό έκανα επειδή έχουμε αυτούς τους αισθητήρες.
<img width="762" alt="screen shot 2015-10-01 at 8 03 02 pm" src="https://cloud.githubusercontent.com/assets/7872396/10227698/87f59634-6877-11e5-8aa4-9ec78882bfe2.png">

**Comment by xaxiris** [comment]
Νομίζω πρέπει να το αλλάξουμε λίγο, γιατί θέλουμε να έχουμε μεταβλητούς τους αισθητήρες και να μπορούμε να προσθέσουμε και άλλους...

**Comment by mbalamat** [comment]
OK το ψάχνω λίγο και μόλις το τελειώσω θα το προσθέσω.

**Comment by xaxiris** [comment]
Περιμένω το νέο σχέδιο και μέρα και ώρα συνάντησης

**Comment by xaxiris** [comment]
![screen shot 2015-10-03 at 1 32 38](https://cloud.githubusercontent.com/assets/8019846/10259243/bcb0153c-696e-11e5-807f-e602019a0030.png)

**Comment by xaxiris** [comment]
Σε αυτή τη βάση μάλλον θα δουλέψουμε

**Comment by mbalamat** [comment]
Oκ θα την υλοποιήσω και θα κλείσω το issue μόλις το κάνω.

Στις Σάβ, 3 Οκτ 2015 στις 1:35 π.μ., ο/η Loukianos Nikolaos Xaxiris <
notifications@github.com> έγραψε:

**Comment by mbalamat** [comment]
οκ done
