### ISSUE TITLE
openshift_address

### ISSUE THREAD

**Issue by xaxiris** [ellak-monades-aristeias/WeatherPiStation#3]
Έχουμε νέα διεύθυνση στο openshift για δεδομένα? αν ναι ποιά είναι αυτή?

**Comment by tolvog** [comment]
Δε λειτουργει το gear?

Γενικα προτινουν τη χρηση των github pages απο το ΕΛ/ΛΑΚ!

Έχουμε νέα διεύθυνση στο openshift για δεδομένα? αν ναι ποιά είναι αυτή?

—
Reply to this email directly or view it on GitHub
https://github.com/ellak-monades-aristeias/WeatherPiStation/issues/3.

**Comment by mbalamat** [comment]
ok οτιδήποτε

**Comment by mbalamat** [comment]
https://weatherpistation-mbalamat.rhcloud.com/
