### ISSUE TITLE
Αλλαγή Αρχιτεκτονικής

### ISSUE THREAD

**Issue by mbalamat** [ellak-monades-aristeias/WeatherPiStation#4]
Πρέπει να γίνει αλλαγή της υπάρχουσας αρχιτεκτονικής προκειμένου να μπορούμε να υποστηρίξουμε 3ων ειδών clients: 1) clients που απλά θέλουν να δουν τα δεδομένα, 2) clients που θα μπορούν να τραβούν δεδομένα και να τα χρησιμοποιούν (εφαρμογές), 3) clients που εισάγουν δεδομένα στη βάση δηλαδή τα Pi με το airPi.

**Comment by xaxiris** [comment]
Ρίξε μια ματιά ξανά στα ζητούμενα:
2. Εμφάνιση των πληροφοριών με σωστό τρόπο, ανεξάρτητα από τις μετρήσεις κάθε raspberry pi. Το τωρινό σύστημα έχει την δυνατότητα να αποθηκεύει στην βάση διαφορετικό πλήθος μετρήσεων ανά raspberry pi. Για παράδειγμα κάποιο raspberry pi μπορεί να έχει μόνο αισθητήρα θερμοκρασίας. Δεν έχει όμως την δυνατότητα να εμφανίζονται σωστά οι μετρήσεις δεν είναι σε όλα τα raspberry pi οι ίδιες.
1. Εμφάνιση μετρήσεων από συγκεκριμένο raspberri pi (αναζήτηση με βάση το id).
2. Εμφάνιση μόνο συγκεκριμένου τύπου μετρήσεων (αναζήτηση με βάση τον τύπο της μέτρησης).
3. Εμφάνιση μετρήσεων ανάμεσα σε συγκεκριμένες ημερομηνίες (αναζήτηση με βάση τον χρόνο).
4. Συνδυασμοί των αναζητήσεων 3, 4, 5.
5. Οι λειτουργίες 2, 3, 4, 5, 6 να είναι διαθέσιμες και μέσω html (για προβολή σε webbrowser) αλλά και σε μορφή json (για να είναι διαθέσιμες σε άλλα προγράμματα μέσω api).

**Comment by mbalamat** [comment]
Νομίζω είναι η καλύτερη αρχιτεκτονική από αυτές που συζητήσαμε.
<img width="393" alt="screen shot 2015-10-04 at 12 51 47 pm" src="https://cloud.githubusercontent.com/assets/7872396/10267633/2d3351f8-6aa4-11e5-8a4b-1d9b24d834fa.png">

**Comment by xaxiris** [comment]
Ok
