### ISSUE TITLE
Api

### ISSUE THREAD

**Issue by xaxiris** [ellak-monades-aristeias/WeatherPiStation#6]
Πως πάει το api το ετοιμάζουμε; Δες και το issue το χθεσινό

**Comment by mbalamat** [comment]
Ναι, θα φτιάξω 2 αρχεία ένα push.php που θα το χρησιμοποιούν μόνο τα pi για να γράφουν στη βάση και ένα pull.php το οποίο θα το χρησιμοποιούν οι χρήστες για να τραβούν πληροφορία με ένα API κλειδί και στις 2 περιπτώσεις.

**Comment by xaxiris** [comment]
Ok με το API
